//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalogo_Biblioteca.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogo
    {
        public int ID_LIBRO { get; set; }
        public string TITULO { get; set; }
        public string TEMA { get; set; }
        public string AUTOR { get; set; }
        public Nullable<int> AÑO { get; set; }
        public string FORMATO { get; set; }
        public Nullable<int> HOJAS { get; set; }
        public string MEGA { get; set; }
    }
}
